load("@rules_elixir//impl:defs.bzl", "elixir_library", "elixir_script", "mix_project")

def autogenerated_targets():
  elixir_library(
    name = "common",
    srcs = ["common.ex"],
    compile_deps = [],
    runtime_deps = [],
    visibility = ["//visibility:public"]
  )
  elixir_library(
    name = "compiletime_util",
    srcs = ["compiletime_util.ex"],
    compile_deps = [],
    runtime_deps = [],
    visibility = ["//visibility:public"]
  )
  elixir_library(
    name = "macros",
    srcs = ["macros.ex"],
    compile_deps = [],
    runtime_deps = [],
    exported_deps = [],
    visibility = ["//visibility:public"]
  )

