load("@rules_elixir//impl:autogenerated_helpers.bzl", "elixir_libraries")

def autogenerated_targets(overrides = {}):
  attrs = {
    "common": {
                "name": "common",
                "srcs": ["common.ex"],
                "compile_deps": [],
                "visibility": ["//visibility:public"]
              },
    "compiletime_util": {
                          "name": "compiletime_util",
                          "srcs": ["compiletime_util.ex"],
                          "compile_deps": [],
                          "visibility": ["//visibility:public"]
                        },
    "macros": {
                "name": "macros",
                "srcs": ["macros.ex"],
                "compile_deps": [],
                "exported_deps": [],
                "visibility": ["//visibility:public"]
              }
  }
  elixir_libraries(attrs, overrides)

