load("@rules_elixir//impl:defs.bzl", "elixir_library", "elixir_script", "mix_project")

def autogenerated_targets():
  elixir_library(
    name = "only_runtime",
    srcs = ["only_runtime.ex"],
    compile_deps = [],
    visibility = ["//visibility:public"]
  )

