load("@rules_elixir//impl:autogenerated_helpers.bzl", "elixir_libraries")

def autogenerated_targets(overrides = {}):
  attrs = {
    "only_runtime": {
                      "name": "only_runtime",
                      "srcs": ["only_runtime.ex"],
                      "compile_deps": [],
                      "visibility": ["//visibility:public"]
                    }
  }
  elixir_libraries(attrs, overrides)

