load("//impl:defs.bzl", "elixir_library")

elixir_library(
    name = "common",
    srcs = ["common.ex"],
    visibility = ["//impl/tools:__subpackages__"],
)

elixir_library(
    name = "bazel",
    srcs = ["bazel.ex"],
    visibility = ["//impl/tools:__subpackages__"],
)
