load("@rules_elixir//impl:defs.bzl", "elixir_library", "elixir_script", "mix_project")

def autogenerated_targets():
  elixir_library(
    name = "circular_structs",
    srcs = ["circular_structs.ex"],
    compile_deps = [":struct_a", ":struct_b"],
    visibility = ["//visibility:public"]
  )
  elixir_library(
    name = "struct_a",
    srcs = ["struct_a.ex"],
    compile_deps = ["//test/mix/circular_structs:circular_structs_third_party"],
    visibility = ["//visibility:public"]
  )
  elixir_library(
    name = "struct_b",
    srcs = ["struct_b.ex"],
    compile_deps = ["//test/mix/circular_structs:circular_structs_third_party"],
    visibility = ["//visibility:public"]
  )

