load("@rules_elixir//impl:defs.bzl", "elixir_library", "elixir_script", "mix_project")

def autogenerated_targets():
  mix_project(
    name = "circular_structs",
    mix_env = "dev",
    config_path = "config/config.exs",
    deps_path = "deps",
    deps_names = ["decimal", "ecto", "poolboy"],
    apps_names = ["circular_structs"],
    lib_targets = ["//test/mix/circular_structs/lib:struct_a",
                   "//test/mix/circular_structs/lib:struct_b",
                   "//test/mix/circular_structs/lib:circular_structs"],
    build_path = "_build/dev"
  )

