load("@rules_elixir//impl:defs.bzl", "elixir_library", "elixir_script", "mix_project")

def autogenerated_targets():
  elixir_library(
    name = "app_one",
    srcs = ["app_one.ex"],
    compile_deps = ["//test/mix/umbrella/apps/common/lib:macros"],
    runtime_deps = ["//test/mix/umbrella/apps/common/lib:common"],
    macroexpand_deps = [],
    visibility = ["//visibility:public"]
  )

