load("@rules_elixir//impl:autogenerated_helpers.bzl", "elixir_libraries")

def autogenerated_targets(overrides = {}):
  attrs = {
    "app_one": {
                 "name": "app_one",
                 "srcs": ["app_one.ex"],
                 "compile_deps": [":example_ecto_schema", ":macros",
                                  "//test/mix/umbrella:config",
                                  "//test/mix/umbrella:external_dep_jason"],
                 "visibility": ["//visibility:public"]
               },
    "example_ecto_schema": {
                             "name": "example_ecto_schema",
                             "srcs": ["example_ecto_schema.ex"],
                             "compile_deps": ["//test/mix/umbrella:external_dep_ecto"],
                             "visibility": ["//visibility:public"]
                           },
    "macros": {
                "name": "macros",
                "srcs": ["macros.ex"],
                "compile_deps": [],
                "exported_deps": ["//test/mix/umbrella/apps/common/lib:compiletime_util",
                                  "//test/mix/umbrella:external_dep_common_library"],
                "visibility": ["//visibility:public"]
              }
  }
  elixir_libraries(attrs, overrides)

