load("@rules_elixir//impl:defs.bzl", "elixir_library", "elixir_script", "mix_project")

def autogenerated_targets():
  elixir_library(
    name = "app_two",
    srcs = ["app_two.ex"],
    compile_deps = [],
    runtime_deps = [":some_module",
                    "//test/mix/umbrella/apps/common/lib:common"],
    macroexpand_deps = [],
    visibility = ["//visibility:public"]
  )
  elixir_library(
    name = "some_module",
    srcs = ["some_module.ex"],
    compile_deps = [],
    runtime_deps = [],
    macroexpand_deps = [],
    visibility = ["//visibility:public"]
  )

