load("@rules_elixir//impl:defs.bzl", "elixir_library", "elixir_script", "mix_project")

def autogenerated_targets():
  mix_project(
    name = "umbrella",
    mix_env = "dev",
    config_path = "config/config.exs",
    deps_path = "deps",
    deps_names = ["jason", "mimerl"],
    lib_targets = ["//test/mix/umbrella/apps/common/lib:macros",
                   "//test/mix/umbrella/apps/app_two/lib:app_two",
                   "//test/mix/umbrella/apps/app_one/lib:app_one",
                   "//test/mix/umbrella/apps/common/lib:common",
                   "//test/mix/umbrella/apps/app_two/lib:some_module"],
    apps_path = "apps",
    build_path = "_build/dev"
  )

