load("@rules_elixir//impl:defs.bzl", "mix_project")

def autogenerated_targets(overrides = {}):
  mix_project(
    name = "umbrella_dev",
    mix_env = "dev",
    config_path = "config/config.exs",
    build_path = "_build/dev",
    apps_path = "apps",
    deps_graph = {
                   "app_one": {
                                "deps": ["common", "ecto_sql", "jason",
                                         "postgrex"],
                                "in_umbrella": True,
                                "inputs": ["app_one", "common",
                                           "common_library", "connection",
                                           "db_connection", "decimal", "ecto",
                                           "ecto_sql", "jason", "postgrex",
                                           "telemetry"],
                                "manager": "mix",
                                "path": "apps/app_one"
                              },
                   "app_two": {
                                "deps": ["common", "mimerl", "only_runtime",
                                         "timex"],
                                "in_umbrella": True,
                                "inputs": ["app_two", "certifi", "combine",
                                           "common", "common_library",
                                           "gettext", "hackney", "idna",
                                           "metrics", "mimerl", "only_runtime",
                                           "parse_trans", "ssl_verify_fun",
                                           "timex", "tzdata",
                                           "unicode_util_compat"],
                                "manager": "mix",
                                "path": "apps/app_two"
                              },
                   "certifi": {
                                "deps": ["parse_trans"],
                                "in_umbrella": False,
                                "inputs": ["certifi", "parse_trans"],
                                "manager": "rebar3",
                                "path": "deps/certifi"
                              },
                   "combine": {
                                "deps": [],
                                "in_umbrella": False,
                                "inputs": ["combine"],
                                "manager": "mix",
                                "path": "deps/combine"
                              },
                   "common": {
                               "deps": ["common_library"],
                               "in_umbrella": True,
                               "inputs": ["common", "common_library"],
                               "manager": "mix",
                               "path": "apps/common"
                             },
                   "common_library": {
                                       "deps": [],
                                       "in_umbrella": False,
                                       "inputs": ["common_library"],
                                       "manager": "mix",
                                       "path": "libraries/common_library"
                                     },
                   "connection": {
                                   "deps": [],
                                   "in_umbrella": False,
                                   "inputs": ["connection"],
                                   "manager": "mix",
                                   "path": "deps/connection"
                                 },
                   "db_connection": {
                                      "deps": ["connection"],
                                      "in_umbrella": False,
                                      "inputs": ["connection", "db_connection"],
                                      "manager": "mix",
                                      "path": "deps/db_connection"
                                    },
                   "decimal": {
                                "deps": [],
                                "in_umbrella": False,
                                "inputs": ["decimal"],
                                "manager": "mix",
                                "path": "deps/decimal"
                              },
                   "ecto": {
                             "deps": ["decimal", "jason"],
                             "in_umbrella": False,
                             "inputs": ["decimal", "ecto", "jason"],
                             "manager": "mix",
                             "path": "deps/ecto"
                           },
                   "ecto_sql": {
                                 "deps": ["db_connection", "ecto", "postgrex",
                                          "telemetry"],
                                 "in_umbrella": False,
                                 "inputs": ["connection", "db_connection",
                                            "decimal", "ecto", "ecto_sql",
                                            "jason", "postgrex", "telemetry"],
                                 "manager": "mix",
                                 "path": "deps/ecto_sql"
                               },
                   "gettext": {
                                "deps": [],
                                "in_umbrella": False,
                                "inputs": ["gettext"],
                                "manager": "mix",
                                "path": "deps/gettext"
                              },
                   "hackney": {
                                "deps": ["certifi", "idna", "metrics", "mimerl",
                                         "ssl_verify_fun"],
                                "in_umbrella": False,
                                "inputs": ["certifi", "hackney", "idna",
                                           "metrics", "mimerl", "parse_trans",
                                           "ssl_verify_fun",
                                           "unicode_util_compat"],
                                "manager": "rebar3",
                                "path": "deps/hackney"
                              },
                   "idna": {
                             "deps": ["unicode_util_compat"],
                             "in_umbrella": False,
                             "inputs": ["idna", "unicode_util_compat"],
                             "manager": "rebar3",
                             "path": "deps/idna"
                           },
                   "jason": {
                              "deps": ["decimal"],
                              "in_umbrella": False,
                              "inputs": ["decimal", "jason"],
                              "manager": "mix",
                              "path": "deps/jason"
                            },
                   "metrics": {
                                "deps": [],
                                "in_umbrella": False,
                                "inputs": ["metrics"],
                                "manager": "rebar3",
                                "path": "deps/metrics"
                              },
                   "mimerl": {
                               "deps": [],
                               "in_umbrella": False,
                               "inputs": ["mimerl"],
                               "manager": "rebar3",
                               "path": "deps/mimerl"
                             },
                   "only_runtime": {
                                     "deps": [],
                                     "in_umbrella": True,
                                     "inputs": ["only_runtime"],
                                     "manager": "mix",
                                     "path": "apps/only_runtime"
                                   },
                   "parse_trans": {
                                    "deps": [],
                                    "in_umbrella": False,
                                    "inputs": ["parse_trans"],
                                    "manager": "rebar3",
                                    "path": "deps/parse_trans"
                                  },
                   "postgrex": {
                                 "deps": ["connection", "db_connection",
                                          "decimal", "jason"],
                                 "in_umbrella": False,
                                 "inputs": ["connection", "db_connection",
                                            "decimal", "jason", "postgrex"],
                                 "manager": "mix",
                                 "path": "deps/postgrex"
                               },
                   "ssl_verify_fun": {
                                       "deps": [],
                                       "in_umbrella": False,
                                       "inputs": ["ssl_verify_fun"],
                                       "manager": "mix",
                                       "path": "deps/ssl_verify_fun"
                                     },
                   "telemetry": {
                                  "deps": [],
                                  "in_umbrella": False,
                                  "inputs": ["telemetry"],
                                  "manager": "rebar3",
                                  "path": "deps/telemetry"
                                },
                   "timex": {
                              "deps": ["combine", "gettext", "tzdata"],
                              "in_umbrella": False,
                              "inputs": ["certifi", "combine", "gettext",
                                         "hackney", "idna", "metrics", "mimerl",
                                         "parse_trans", "ssl_verify_fun",
                                         "timex", "tzdata",
                                         "unicode_util_compat"],
                              "manager": "mix",
                              "path": "deps/timex"
                            },
                   "tzdata": {
                               "deps": ["hackney"],
                               "in_umbrella": False,
                               "inputs": ["certifi", "hackney", "idna",
                                          "metrics", "mimerl", "parse_trans",
                                          "ssl_verify_fun", "tzdata",
                                          "unicode_util_compat"],
                               "manager": "mix",
                               "path": "deps/tzdata"
                             },
                   "unicode_util_compat": {
                                            "deps": [],
                                            "in_umbrella": False,
                                            "inputs": ["unicode_util_compat"],
                                            "manager": "rebar3",
                                            "path": "deps/unicode_util_compat"
                                          }
                 }
  )
  mix_project(
    name = "umbrella_test",
    mix_env = "test",
    config_path = "config/config.exs",
    build_path = "_build/test",
    apps_path = "apps",
    deps_graph = {
                   "app_one": {
                                "deps": ["common", "ecto_sql", "jason",
                                         "postgrex"],
                                "in_umbrella": True,
                                "inputs": ["app_one", "common",
                                           "common_library", "connection",
                                           "db_connection", "decimal", "ecto",
                                           "ecto_sql", "jason", "postgrex",
                                           "telemetry", "test_helper_library"],
                                "manager": "mix",
                                "path": "apps/app_one"
                              },
                   "app_two": {
                                "deps": ["common", "mimerl", "only_runtime",
                                         "timex"],
                                "in_umbrella": True,
                                "inputs": ["app_two", "certifi", "combine",
                                           "common", "common_library",
                                           "gettext", "hackney", "idna",
                                           "metrics", "mimerl", "only_runtime",
                                           "parse_trans", "ssl_verify_fun",
                                           "test_helper_library", "timex",
                                           "tzdata", "unicode_util_compat"],
                                "manager": "mix",
                                "path": "apps/app_two"
                              },
                   "certifi": {
                                "deps": ["parse_trans"],
                                "in_umbrella": False,
                                "inputs": ["certifi", "parse_trans"],
                                "manager": "rebar3",
                                "path": "deps/certifi"
                              },
                   "combine": {
                                "deps": [],
                                "in_umbrella": False,
                                "inputs": ["combine"],
                                "manager": "mix",
                                "path": "deps/combine"
                              },
                   "common": {
                               "deps": ["common_library", "test_helper_library"],
                               "in_umbrella": True,
                               "inputs": ["common", "common_library",
                                          "test_helper_library"],
                               "manager": "mix",
                               "path": "apps/common"
                             },
                   "common_library": {
                                       "deps": [],
                                       "in_umbrella": False,
                                       "inputs": ["common_library"],
                                       "manager": "mix",
                                       "path": "libraries/common_library"
                                     },
                   "connection": {
                                   "deps": [],
                                   "in_umbrella": False,
                                   "inputs": ["connection"],
                                   "manager": "mix",
                                   "path": "deps/connection"
                                 },
                   "db_connection": {
                                      "deps": ["connection"],
                                      "in_umbrella": False,
                                      "inputs": ["connection", "db_connection"],
                                      "manager": "mix",
                                      "path": "deps/db_connection"
                                    },
                   "decimal": {
                                "deps": [],
                                "in_umbrella": False,
                                "inputs": ["decimal"],
                                "manager": "mix",
                                "path": "deps/decimal"
                              },
                   "ecto": {
                             "deps": ["decimal", "jason"],
                             "in_umbrella": False,
                             "inputs": ["decimal", "ecto", "jason"],
                             "manager": "mix",
                             "path": "deps/ecto"
                           },
                   "ecto_sql": {
                                 "deps": ["db_connection", "ecto", "postgrex",
                                          "telemetry"],
                                 "in_umbrella": False,
                                 "inputs": ["connection", "db_connection",
                                            "decimal", "ecto", "ecto_sql",
                                            "jason", "postgrex", "telemetry"],
                                 "manager": "mix",
                                 "path": "deps/ecto_sql"
                               },
                   "gettext": {
                                "deps": [],
                                "in_umbrella": False,
                                "inputs": ["gettext"],
                                "manager": "mix",
                                "path": "deps/gettext"
                              },
                   "hackney": {
                                "deps": ["certifi", "idna", "metrics", "mimerl",
                                         "ssl_verify_fun"],
                                "in_umbrella": False,
                                "inputs": ["certifi", "hackney", "idna",
                                           "metrics", "mimerl", "parse_trans",
                                           "ssl_verify_fun",
                                           "unicode_util_compat"],
                                "manager": "rebar3",
                                "path": "deps/hackney"
                              },
                   "idna": {
                             "deps": ["unicode_util_compat"],
                             "in_umbrella": False,
                             "inputs": ["idna", "unicode_util_compat"],
                             "manager": "rebar3",
                             "path": "deps/idna"
                           },
                   "jason": {
                              "deps": ["decimal"],
                              "in_umbrella": False,
                              "inputs": ["decimal", "jason"],
                              "manager": "mix",
                              "path": "deps/jason"
                            },
                   "metrics": {
                                "deps": [],
                                "in_umbrella": False,
                                "inputs": ["metrics"],
                                "manager": "rebar3",
                                "path": "deps/metrics"
                              },
                   "mimerl": {
                               "deps": [],
                               "in_umbrella": False,
                               "inputs": ["mimerl"],
                               "manager": "rebar3",
                               "path": "deps/mimerl"
                             },
                   "only_runtime": {
                                     "deps": [],
                                     "in_umbrella": True,
                                     "inputs": ["only_runtime"],
                                     "manager": "mix",
                                     "path": "apps/only_runtime"
                                   },
                   "parse_trans": {
                                    "deps": [],
                                    "in_umbrella": False,
                                    "inputs": ["parse_trans"],
                                    "manager": "rebar3",
                                    "path": "deps/parse_trans"
                                  },
                   "postgrex": {
                                 "deps": ["connection", "db_connection",
                                          "decimal", "jason"],
                                 "in_umbrella": False,
                                 "inputs": ["connection", "db_connection",
                                            "decimal", "jason", "postgrex"],
                                 "manager": "mix",
                                 "path": "deps/postgrex"
                               },
                   "ssl_verify_fun": {
                                       "deps": [],
                                       "in_umbrella": False,
                                       "inputs": ["ssl_verify_fun"],
                                       "manager": "mix",
                                       "path": "deps/ssl_verify_fun"
                                     },
                   "telemetry": {
                                  "deps": [],
                                  "in_umbrella": False,
                                  "inputs": ["telemetry"],
                                  "manager": "rebar3",
                                  "path": "deps/telemetry"
                                },
                   "test_helper_library": {
                                            "deps": [],
                                            "in_umbrella": False,
                                            "inputs": ["test_helper_library"],
                                            "manager": "mix",
                                            "path": "libraries/test_helper_library"
                                          },
                   "timex": {
                              "deps": ["combine", "gettext", "tzdata"],
                              "in_umbrella": False,
                              "inputs": ["certifi", "combine", "gettext",
                                         "hackney", "idna", "metrics", "mimerl",
                                         "parse_trans", "ssl_verify_fun",
                                         "timex", "tzdata",
                                         "unicode_util_compat"],
                              "manager": "mix",
                              "path": "deps/timex"
                            },
                   "tzdata": {
                               "deps": ["hackney"],
                               "in_umbrella": False,
                               "inputs": ["certifi", "hackney", "idna",
                                          "metrics", "mimerl", "parse_trans",
                                          "ssl_verify_fun", "tzdata",
                                          "unicode_util_compat"],
                               "manager": "mix",
                               "path": "deps/tzdata"
                             },
                   "unicode_util_compat": {
                                            "deps": [],
                                            "in_umbrella": False,
                                            "inputs": ["unicode_util_compat"],
                                            "manager": "rebar3",
                                            "path": "deps/unicode_util_compat"
                                          }
                 }
  )
  mix_project(
    name = "umbrella_prod",
    mix_env = "prod",
    config_path = "config/config.exs",
    build_path = "_build/prod",
    apps_path = "apps",
    deps_graph = {
                   "app_one": {
                                "deps": ["common", "ecto_sql", "jason",
                                         "postgrex"],
                                "in_umbrella": True,
                                "inputs": ["app_one", "common",
                                           "common_library", "connection",
                                           "db_connection", "decimal", "ecto",
                                           "ecto_sql", "jason", "postgrex",
                                           "telemetry"],
                                "manager": "mix",
                                "path": "apps/app_one"
                              },
                   "app_two": {
                                "deps": ["common", "mimerl", "only_runtime",
                                         "timex"],
                                "in_umbrella": True,
                                "inputs": ["app_two", "certifi", "combine",
                                           "common", "common_library",
                                           "gettext", "hackney", "idna",
                                           "metrics", "mimerl", "only_runtime",
                                           "parse_trans", "ssl_verify_fun",
                                           "timex", "tzdata",
                                           "unicode_util_compat"],
                                "manager": "mix",
                                "path": "apps/app_two"
                              },
                   "certifi": {
                                "deps": ["parse_trans"],
                                "in_umbrella": False,
                                "inputs": ["certifi", "parse_trans"],
                                "manager": "rebar3",
                                "path": "deps/certifi"
                              },
                   "combine": {
                                "deps": [],
                                "in_umbrella": False,
                                "inputs": ["combine"],
                                "manager": "mix",
                                "path": "deps/combine"
                              },
                   "common": {
                               "deps": ["common_library"],
                               "in_umbrella": True,
                               "inputs": ["common", "common_library"],
                               "manager": "mix",
                               "path": "apps/common"
                             },
                   "common_library": {
                                       "deps": [],
                                       "in_umbrella": False,
                                       "inputs": ["common_library"],
                                       "manager": "mix",
                                       "path": "libraries/common_library"
                                     },
                   "connection": {
                                   "deps": [],
                                   "in_umbrella": False,
                                   "inputs": ["connection"],
                                   "manager": "mix",
                                   "path": "deps/connection"
                                 },
                   "db_connection": {
                                      "deps": ["connection"],
                                      "in_umbrella": False,
                                      "inputs": ["connection", "db_connection"],
                                      "manager": "mix",
                                      "path": "deps/db_connection"
                                    },
                   "decimal": {
                                "deps": [],
                                "in_umbrella": False,
                                "inputs": ["decimal"],
                                "manager": "mix",
                                "path": "deps/decimal"
                              },
                   "ecto": {
                             "deps": ["decimal", "jason"],
                             "in_umbrella": False,
                             "inputs": ["decimal", "ecto", "jason"],
                             "manager": "mix",
                             "path": "deps/ecto"
                           },
                   "ecto_sql": {
                                 "deps": ["db_connection", "ecto", "postgrex",
                                          "telemetry"],
                                 "in_umbrella": False,
                                 "inputs": ["connection", "db_connection",
                                            "decimal", "ecto", "ecto_sql",
                                            "jason", "postgrex", "telemetry"],
                                 "manager": "mix",
                                 "path": "deps/ecto_sql"
                               },
                   "gettext": {
                                "deps": [],
                                "in_umbrella": False,
                                "inputs": ["gettext"],
                                "manager": "mix",
                                "path": "deps/gettext"
                              },
                   "hackney": {
                                "deps": ["certifi", "idna", "metrics", "mimerl",
                                         "ssl_verify_fun"],
                                "in_umbrella": False,
                                "inputs": ["certifi", "hackney", "idna",
                                           "metrics", "mimerl", "parse_trans",
                                           "ssl_verify_fun",
                                           "unicode_util_compat"],
                                "manager": "rebar3",
                                "path": "deps/hackney"
                              },
                   "idna": {
                             "deps": ["unicode_util_compat"],
                             "in_umbrella": False,
                             "inputs": ["idna", "unicode_util_compat"],
                             "manager": "rebar3",
                             "path": "deps/idna"
                           },
                   "jason": {
                              "deps": ["decimal"],
                              "in_umbrella": False,
                              "inputs": ["decimal", "jason"],
                              "manager": "mix",
                              "path": "deps/jason"
                            },
                   "metrics": {
                                "deps": [],
                                "in_umbrella": False,
                                "inputs": ["metrics"],
                                "manager": "rebar3",
                                "path": "deps/metrics"
                              },
                   "mimerl": {
                               "deps": [],
                               "in_umbrella": False,
                               "inputs": ["mimerl"],
                               "manager": "rebar3",
                               "path": "deps/mimerl"
                             },
                   "only_runtime": {
                                     "deps": [],
                                     "in_umbrella": True,
                                     "inputs": ["only_runtime"],
                                     "manager": "mix",
                                     "path": "apps/only_runtime"
                                   },
                   "parse_trans": {
                                    "deps": [],
                                    "in_umbrella": False,
                                    "inputs": ["parse_trans"],
                                    "manager": "rebar3",
                                    "path": "deps/parse_trans"
                                  },
                   "postgrex": {
                                 "deps": ["connection", "db_connection",
                                          "decimal", "jason"],
                                 "in_umbrella": False,
                                 "inputs": ["connection", "db_connection",
                                            "decimal", "jason", "postgrex"],
                                 "manager": "mix",
                                 "path": "deps/postgrex"
                               },
                   "ssl_verify_fun": {
                                       "deps": [],
                                       "in_umbrella": False,
                                       "inputs": ["ssl_verify_fun"],
                                       "manager": "mix",
                                       "path": "deps/ssl_verify_fun"
                                     },
                   "telemetry": {
                                  "deps": [],
                                  "in_umbrella": False,
                                  "inputs": ["telemetry"],
                                  "manager": "rebar3",
                                  "path": "deps/telemetry"
                                },
                   "timex": {
                              "deps": ["combine", "gettext", "tzdata"],
                              "in_umbrella": False,
                              "inputs": ["certifi", "combine", "gettext",
                                         "hackney", "idna", "metrics", "mimerl",
                                         "parse_trans", "ssl_verify_fun",
                                         "timex", "tzdata",
                                         "unicode_util_compat"],
                              "manager": "mix",
                              "path": "deps/timex"
                            },
                   "tzdata": {
                               "deps": ["hackney"],
                               "in_umbrella": False,
                               "inputs": ["certifi", "hackney", "idna",
                                          "metrics", "mimerl", "parse_trans",
                                          "ssl_verify_fun", "tzdata",
                                          "unicode_util_compat"],
                               "manager": "mix",
                               "path": "deps/tzdata"
                             },
                   "unicode_util_compat": {
                                            "deps": [],
                                            "in_umbrella": False,
                                            "inputs": ["unicode_util_compat"],
                                            "manager": "rebar3",
                                            "path": "deps/unicode_util_compat"
                                          }
                 }
  )

