load("//impl:defs.bzl", "elixir_library", "elixir_script")

def autogenerated_targets():
  elixir_library(
    name = "bleh",
    srcs = ["bleh.ex"],
    compile_deps = ["//test/mix/zzz/lib:macros"],
    runtime_deps = [],
    visibility = ["//visibility:public"]
  )